### ISSUE TITLE
UI 설계

### ISSUE THREAD

**Issue by pjiyun123** [pjiyun123/mmp-groupware-project#21]
* 카카오 오븐을 이용한 UI 설계

**Comment by pjiyun123** [comment]
* UI 설계 링크
https://ovenapp.io/view/3tZK04bHPC0ATexdfRDX3zPXoQmc7Mwv/1875M

**Comment by hyo05095** [comment]
- UI설계 수정링크
https://ovenapp.io/view/ackrycsvPX5pxKnlTFR44crUzTfLNxlU/
